### ISSUE TITLE
Storage location for experiment-level objects

### ISSUE THREAD

**Issue by ebianchi** [DAIRLab/dair_pll#7]
With some discussion in PR #6 , it would be nice to have an experiment-level way of keeping track of storage locations.  Currently there is only formal tracking of study-level storage locations.  `file_utils.py` contains some hacked way of looking up experiment-level storage locations, though this would ideally be replaced by an addition to the `SupervisedLearningExperimentConfig` class like `experiment_storage_name` or similar.

**Comment by mshalm** [comment]
Implemented in #12 .
